backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
media_folder: "assets/images"

collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true # To hide preview pane
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "date" }
      - {
          label: "Author",
          name: "author",
          widget: "relation",
          collection: "authors",
          displayFields: ["name"],
          searchFields: ["display_name"],
          valueField: "name",
        }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "authors"
    label: "Authors"
    folder: "_authors/"
    create: true
    editor:
      preview: true # To hide preview pane
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "author" }
      - { label: "Short Name", name: "name", widget: "string" }
      - { label: "Display Name", name: "display_name", widget: "string" }
      - { label: "Position", name: "position", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    editor:
      preview: true # To hide preview pane
    files:
      - label: "About Page"
        name: "about"
        file: "about.md"
        fields:
          - { label: "Title", name: "title", widget: "hidden", default: "About" }
          - { label: "Layout", name: "layout", widget: "hidden", default: "about" }
          - { label: "Body", name: "body", widget: "markdown" }

  - name: "config"
    label: "Config"
    editor:
      preview: true
    files:
      - label: "Navigation"
        name: "navigation"
        file: "_data/navigation.yml"
        fields:
          - label: "Navigation Items"
            name: "items"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Link", name: "link", widget: "string" }
